spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app
    username: app
    password: app
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor.sql.BasicBinder: trace
          EnumType: trace
      #springframework.web: DEBUG